"""Cut 12's declared arms: 19 selected + 5 labeled = 24 units, 50 lettered arms."""

from n2_arms import Arm, Sabotage

_SUCC = "succession.py"
_SPEC = "spec.py"
_RECORDS = "world/records.py"
_REDUCE = "intents/reduce.py"
_EVIDENCE = "intents/evidence.py"
_ERRORS = "errors.py"
_SHAPES = "intents/shapes.py"

_ACCEPT = "acceptance/test_successor_admission_acceptance.py"

CUT12_ARMS = (
    Arm("G4u1", "a live failing verification blocks an unreferenced successor",
        Sabotage(_SUCC,
            before='failing = {path: value for path, value in verifications.items() if value.verdict == "failed"}',
            after='failing = {path: value for path, value in verifications.items() if value.verdict == "never"}'),
        ("test_succession.py::test_a_live_failing_verification_blocks_an_unreferenced_successor",)),
    Arm("G4u2", "an unfinished attempt blocks an unreferenced successor",
        Sabotage(_SUCC,
            before='elif row.status == "attempt-without-recorded-outcome":\n            unfinished.add(spec_identity)',
            after='elif row.status == "attempt-without-recorded-outcome":\n            pass'),
        ("test_succession.py::test_an_unfinished_attempt_blocks_an_unreferenced_successor",
         f"{_ACCEPT}::test_u14_a_kill_between_append_and_execution_blocks_the_successor")),
    Arm("G4u3", "a qualifying run-attempt report is a recorded failure",
        Sabotage(_SUCC,
            before='if type(evidence) is shapes.ReportEvidence and evidence.operation == "run-attempt":',
            after='if False:'),
        ("test_succession.py::test_a_run_attempt_report_is_a_recorded_failure",)),
    Arm("G4u4", "a referencing successor lifts every class",
        Sabotage(_SPEC,
            before='    if superseded.identity in unfinished_attempts and candidate.supersedes != superseded.identity:',
            after='    if superseded.identity in unfinished_attempts:'),
        ("test_spec.py::test_g4_a_referencing_successor_lifts_both_classes",
         "test_succession.py::test_an_unfinished_attempt_blocks_an_unreferenced_successor")),
    Arm("G4u5", "a spec in both classes refuses with the recorded-failure reason",
        Sabotage(_SPEC,
            before='return SuccessorRefused(candidate.identity, "an unreferenced successor to a recorded failed replay")\n    if superseded.identity in unfinished_attempts',
            after='pass\n    if superseded.identity in unfinished_attempts'),
        ("test_spec.py::test_g4_a_spec_in_both_classes_refuses_with_the_recorded_failure_reason",
         "test_succession.py::test_overlap_refuses_with_the_recorded_failure_reason")),
    Arm("G4u6a", "a coherent passing superseder lifts the block",
        Sabotage(_SUCC,
            before='active = {value.ref for value in verification_module.active(tuple(verifications.values()))}',
            after='active = {value.ref for value in verifications.values()}'),
        ("test_succession.py::test_a_coherent_passing_superseder_lifts_the_block",)),
    Arm("G4u6b", "a failing superseder keeps the block through the active member",
        Sabotage(_SUCC,
            before='return frozenset(targets[path].spec for path, value in failing.items() if value.ref in active)',
            after='return frozenset(targets[path].spec for path, value in failing.items() if value.ref in active and value.supersedes is None)'),
        ("test_succession.py::test_a_failing_superseder_keeps_the_block_through_the_active_member",)),
    Arm("G4u6c", "an incoherent passing superseder refuses naming itself",
        Sabotage(_SUCC,
            before='if path in failing or value.supersedes in blockers',
            after='if path in failing'),
        ("test_succession.py::test_an_incoherent_passing_superseder_refuses_naming_itself",
         "test_succession.py::test_a_withheld_verification_with_an_incoherent_superseder_refuses_the_superseder")),
    Arm("G4u7a", "a stale or missing stamp refuses naming the path",
        Sabotage(_EVIDENCE,
            before='if stored.semantic_hash_missing(node) or stored.semantic_hash_disagrees(node):',
            after='if False:'),
        ("test_succession.py::test_a_stale_stamp_refuses_naming_the_path",
         "test_succession.py::test_a_missing_stamp_refuses_naming_the_path",
         "test_intent_evidence.py::test_decode_node_refuses_a_stale_stamp",
         "test_intent_evidence.py::test_decode_node_refuses_a_missing_stamp")),
    Arm("G4u7b", "an id naming another path refuses",
        Sabotage(_EVIDENCE,
            before='if not slug or path != f"{kind}/{slug}.md":',
            after='if not slug:'),
        ("test_succession.py::test_an_id_naming_another_path_refuses",
         "test_intent_evidence.py::test_decode_node_refuses_an_id_that_names_another_path")),
    Arm("G4u7c", "an undecodable evidence record refuses, targeted or not",
        Sabotage(_SUCC,
            before='except RecordUndecodable as caught:\n            raise AdmissionEvidenceRefused(f"{kind} unreadable", path) from caught',
            after='except RecordUndecodable:\n            continue'),
        ("test_succession.py::test_an_undecodable_verification_refuses",
         "test_succession.py::test_an_undecodable_untargeted_assessment_refuses")),
    Arm("G4u7d", "an unreadable regular file refuses in either namespace",
        Sabotage(_SUCC,
            before='for path in surface.unreadable:',
            after='for path in ():'),
        ("test_succession.py::test_an_unreadable_regular_file_refuses_in_either_namespace",)),
    Arm("G4u8a", "edge cardinality other than one refuses",
        Sabotage(_SUCC,
            before='if len(edges) != 1:',
            after='if len(edges) == 0:'),
        ("test_succession.py::test_two_verifies_edges_refuse",)),
    Arm("G4u8b", "a target that is not a decoded assessment refuses",
        Sabotage(_SUCC,
            before='if target_path is None or target_path not in assessments:',
            after='if target_path is None:'),
        ("test_succession.py::test_a_target_that_is_not_an_assessment_refuses",)),
    Arm("G4u8c", "a missing target refuses",
        Sabotage(_SUCC,
            before='target_path = by_uid.get(edge.target_uid) if edge.target_uid is not None else None',
            after='target_path = by_uid.get(edge.target_uid) if edge.target_uid is not None else next(iter(assessments), None)'),
        ("test_succession.py::test_a_missing_target_refuses",)),
    Arm("G4u8d", "a deprecated-id target resolves",
        Sabotage(_SUCC,
            before='if edge.relation.target in withheld:',
            after='if edge.relation.target in withheld or edge.relation.target not in index.id_to_uid:'),
        ("test_succession.py::test_a_deprecated_id_target_resolves_and_blocks",)),
    Arm("G4u8e", "a uid collision refuses naming the colliding id",
        Sabotage(_SUCC,
            before='except CollisionError as caught:\n            raise AdmissionEvidenceRefused("record collision", node.id) from caught',
            after='except CollisionError:\n            continue'),
        ("test_succession.py::test_a_uid_collision_refuses_naming_the_colliding_id",)),
    Arm("G4u8f", "an identity mismatch refuses",
        Sabotage(_SUCC,
            before='if target.identity() != value.assessment:',
            after='if False:'),
        ("test_succession.py::test_an_identity_mismatch_refuses",)),
    Arm("G4u8g", "the gate counts outbound edges, not stored relations",
        Sabotage(_SUCC,
            before='for edge in index.outbound_edges(nodes[path].uid)',
            after='for edge in index.outbound_edges(nodes[path].uid) + index.inbound_edges(nodes[path].uid)'),
        ("test_succession.py::test_a_relation_sourced_elsewhere_is_not_this_verifications_edge",)),
    Arm("G4u9a", "a withheld verification without a coherent superseder refuses",
        Sabotage(_SUCC,
            before='raise AdmissionEvidenceRefused("verification oversized", path)',
            after='continue'),
        ("test_succession.py::test_a_withheld_verification_without_a_superseder_refuses",)),
    Arm("G4u9b", "a withheld verification with a coherent superseder is skipped",
        Sabotage(_SUCC,
            before='if ref.startswith("verification:") and not any(',
            after='if ref.startswith("verification:") and any('),
        ("test_succession.py::test_a_withheld_verification_with_a_coherent_superseder_is_skipped",
         "test_succession.py::test_a_withheld_verification_without_a_superseder_refuses")),
    Arm("G4u9c", "a withheld assessment targeted by a failing verification refuses",
        Sabotage(_SUCC,
            before='if edge.relation.target in withheld:\n            raise AdmissionEvidenceRefused("verification target unreadable", path)',
            after='if edge.relation.target in withheld:\n            continue'),
        ("test_succession.py::test_a_withheld_assessment_targeted_by_a_failing_verification_refuses",)),
    Arm("G4u9d", "a decoded node claiming a withheld path's id is a collision",
        Sabotage(_SUCC,
            before='if index.resolve_uid(ref) is not None:\n            raise AdmissionEvidenceRefused("record collision", ref)',
            after='if False:\n            raise AdmissionEvidenceRefused("record collision", ref)'),
        ("test_succession.py::test_a_decoded_node_claiming_a_withheld_paths_id_is_a_collision",)),
    Arm("G4u9e", "the ceiling is exact: RECORD_CEILING bytes capture, one more is withheld",
        Sabotage(_RECORDS,
            before='return "withheld" if len(data) > RECORD_CEILING else data',
            after='return "withheld" if len(data) >= RECORD_CEILING else data'),
        ("test_record_capture.py::test_an_oversized_regular_file_is_withheld_and_named",)),
    Arm("G4u10", "an unresolvable intent for the superseded spec refuses; another spec's does not block",
        Sabotage(_SUCC,
            before='if spec_identity == superseded_identity:\n                raise AdmissionEvidenceRefused(',
            after='if False:\n                raise AdmissionEvidenceRefused('),
        ("test_succession.py::test_a_decayed_run_under_the_superseded_spec_refuses",)),
    Arm("G4u11", "a writer arriving during the act waits and is not consulted",
        Sabotage(_SUCC,
            before='with seam.corpus_lock(root):\n        view = seam.inspect_registered(root)',
            after='if True:\n        view = seam.inspect_registered(root)'),
        (f"{_ACCEPT}::test_u11_a_writer_arriving_during_the_act_waits_and_is_not_consulted",)),
    Arm("G4u12", "nothing durable leaves no trace: the successor is admitted",
        Sabotage(_SPEC,
            before='    return SuccessorAdmitted(candidate.identity)\n\n\ndef _facet_projection',
            after='    return SuccessorRefused(candidate.identity, "phantom")\n\n\ndef _facet_projection'),
        ("test_succession.py::test_the_negative_nothing_durable_admits",
         "test_spec.py::test_g4_a_discarded_failed_attempt_is_undetectable")),
    Arm("G4u13a", "an unopenable root refuses before any lock",
        Sabotage(_SUCC,
            before='except OSError as failure:\n        raise AdmissionEvidenceRefused("root unreadable", str(root)) from failure',
            after='except OSError:\n        return'),
        ("test_succession.py::test_an_absent_root_refuses_before_any_lock",
         "test_succession.py::test_a_file_where_the_root_should_be_refuses_as_unreadable")),
    Arm("G4u13b", "a non-well-formed chain refuses",
        Sabotage(_SUCC,
            before='if type(view) is not WellFormedView:',
            after='if False:'),
        ("test_succession.py::test_an_unregistered_directory_is_an_absent_chain_and_refuses",
         f"{_ACCEPT}::test_r12u1_an_excised_intent_entry_reads_malformed_and_the_act_refuses")),
    Arm("G4u13c", "an unenumerable namespace refuses; an absent one admits",
        Sabotage(_SUCC,
            before='if surface.uninspectable:',
            after='if False:'),
        ("test_succession.py::test_an_unenumerable_namespace_refuses_for_verification_and_for_run",)),
    Arm("G4u14a", "class 1b reads the record that matched",
        Sabotage(_REDUCE,
            before='return RegistrationReduction((path, record_evidence), pointer_unresolved, tuple(reasons))',
            after='return RegistrationReduction((path, shapes.InertRecord()), pointer_unresolved, tuple(reasons))'),
        ("test_succession.py::test_an_undecodable_sibling_before_the_qualifying_report_still_joins",
         "test_succession.py::test_a_qualifying_report_before_a_qualifying_run_is_the_match",
         "test_intent_reduce.py::test_reduce_registration_first_match_in_order_wins")),
    Arm("G4u14b", "a matched run is a minted run, never a failure",
        Sabotage(_SUCC,
            before='if type(evidence) is shapes.ReportEvidence and evidence.operation == "run-attempt":\n                failures.add(spec_identity)',
            after='if True:\n                failures.add(spec_identity)'),
        ("test_succession.py::test_a_qualifying_run_beside_a_report_joins_nothing",
         "test_succession.py::test_a_qualifying_run_lifts_the_block")),
    Arm("R12u1", "an excised intent entry reads malformed and the act refuses",
        Sabotage(_SUCC,
            before='raise AdmissionEvidenceRefused("chain not well-formed", str(root))',
            after='raise AdmissionEvidenceRefused("root unreadable", str(root))'),
        (f"{_ACCEPT}::test_r12u1_an_excised_intent_entry_reads_malformed_and_the_act_refuses",)),
    Arm("R12u2", "a truncated chain reads refuted under an anchor and the act admits",
        Sabotage(_SUCC,
            before='return admit_successor(candidate, superseded, recorded_failures, unfinished)',
            after='return admit_successor(candidate, superseded, recorded_failures | {superseded.identity}, unfinished)'),
        (f"{_ACCEPT}::test_r12u2_a_truncated_chain_reads_refuted_under_an_anchor_and_the_act_admits",
         "test_succession.py::test_the_negative_nothing_durable_admits")),
    Arm("L7u14", "a kill between append and execution blocks the successor",
        Sabotage(_SUCC,
            before='if row.shape != "assessment-run":\n            continue',
            after='if row.shape != "assessment-run" or row.status == "attempt-without-recorded-outcome":\n            continue'),
        (f"{_ACCEPT}::test_u14_a_kill_between_append_and_execution_blocks_the_successor",)),
    Arm("L7u15", "a wrong-spec publication fails qualification and the intent still blocks",
        Sabotage(_SHAPES,
            before='if evidence.spec_identity != value.spec_identity:\n                return "wrong-spec"',
            after='if evidence.spec_identity != value.spec_identity:\n                return None'),
        ("test_succession.py::test_a_wrong_spec_publication_fails_qualification_and_the_intent_still_blocks",)),
    Arm("L7u16", "a qualifying publication lifts the block",
        Sabotage(_SUCC,
            before='elif row.status == "matched":',
            after='elif row.status == "matched" and not unfinished.add(spec_identity):'),
        ("test_succession.py::test_a_qualifying_run_lifts_the_block",)),
    Arm("K1a", "capture_surface's records equal capture_records' over the default namespaces",
        Sabotage(_RECORDS,
            before='return capture_surface(root, RECORD_NAMESPACES).records',
            after='return capture_surface(root, RECORD_NAMESPACES[:1]).records'),
        ("test_record_capture.py::test_capture_surface_records_equal_capture_records_over_the_default_namespaces",)),
    Arm("K1b", "a non-corpus root holding run records still captures nothing",
        Sabotage(_RECORDS,
            before='if kind != "corpus":\n        return ()',
            after='if kind == "corpus" and False:\n        return ()'),
        ("test_record_capture.py::test_a_non_corpus_root_holding_run_records_still_captures_nothing",)),
    Arm("K2a", "an oversized regular file is withheld and named",
        Sabotage(_RECORDS,
            before='elif payload == "withheld":\n                into.withheld.append(path)',
            after='elif payload == "withheld":\n                pass'),
        ("test_record_capture.py::test_an_oversized_regular_file_is_withheld_and_named",)),
    Arm("K2b", "an unreadable regular file is named, not dropped",
        Sabotage(_RECORDS,
            before='elif payload == "unreadable":\n                into.unreadable.append(path)',
            after='elif payload == "unreadable":\n                pass'),
        ("test_record_capture.py::test_an_unreadable_regular_file_is_named_not_dropped",)),
    Arm("K2c", "an unenumerable namespace is uninspectable; ENOENT is silent",
        Sabotage(_RECORDS,
            before='except OSError as failure:\n        if failure.errno != errno.ENOENT:\n            into.uninspectable.append(prefix)\n        return\n    try:',
            after='except OSError:\n        return\n    try:'),
        ("test_record_capture.py::test_an_unenumerable_namespace_is_uninspectable_and_an_absent_one_is_silent",)),
    Arm("K2d", "a scandir failure is uninspectable unless it is ENOENT",
        Sabotage(_RECORDS,
            before='except OSError as failure:\n            if failure.errno != errno.ENOENT:\n                into.uninspectable.append(prefix)\n            return',
            after='except OSError:\n            return'),
        ("test_record_capture.py::test_a_scandir_failure_is_uninspectable_unless_it_is_enoent",)),
    Arm("K2e", "a directory entry whose classification fails is unreadable, never leaked",
        Sabotage(_RECORDS,
            before='except OSError:\n                into.unreadable.append(path)\n                continue',
            after='except OSError:\n                continue'),
        ("test_record_capture.py::test_a_directory_entry_whose_classification_fails_is_unreadable",)),
    Arm("K3a", "the first match in final order wins",
        Sabotage(_REDUCE,
            before='for path in record_paths:\n        payload = records.get(path)',
            after='for path in reversed(record_paths):\n        payload = records.get(path)'),
        ("test_intent_reduce.py::test_reduce_registration_first_match_in_order_wins",)),
    Arm("K3b", "an undecodable earlier sibling leaves unresolved set beside a later match",
        Sabotage(_REDUCE,
            before='return RegistrationReduction((path, record_evidence), pointer_unresolved, tuple(reasons))',
            after='return RegistrationReduction((path, record_evidence), False, tuple(reasons))'),
        ("test_intent_reduce.py::test_reduce_registration_names_an_undecodable_sibling_beside_a_later_match",)),
    Arm("K3c", "every decoded non-qualifying reason is returned in order",
        Sabotage(_REDUCE,
            before='reasons.append(reason)\n    return RegistrationReduction(None, pointer_unresolved, tuple(reasons))',
            after='reasons.insert(0, reason)\n    return RegistrationReduction(None, pointer_unresolved, tuple(reasons))'),
        ("test_intent_reduce.py::test_reduce_registration_with_no_match_returns_every_reason_in_order",)),
    Arm("K4a", "the refusal carries reason and ref as attributes",
        Sabotage(_ERRORS,
            before='        self.reason = reason\n        self.ref = ref',
            after='        self.reason = ref\n        self.ref = reason'),
        ("test_succession_errors.py::test_it_is_a_science_error_carrying_reason_and_ref",
         "test_succession.py::test_an_absent_root_refuses_before_any_lock")),
    Arm("K4b", "the reason set is closed at the spec's eleven",
        Sabotage(_SUCC,
            before='    "qualification unresolved for the superseded spec",\n)',
            after='    "qualification unresolved for the superseded spec",\n    "phantom",\n)'),
        ("test_succession.py::test_the_reason_set_is_exactly_the_specs_eleven",)),
    Arm("K5", "the core's first body line is cut 3's anchor line",
        Sabotage(_SPEC,
            before='    if superseded.identity in recorded_failures and candidate.supersedes != superseded.identity:',
            after='    if superseded.identity in recorded_failures and (candidate.supersedes != superseded.identity):'),
        ("test_spec.py::test_g4_the_core_keeps_cut_3s_anchor_line",)),
)

_UNIT_OF_LETTERED = {
    "G4u6a": "G4u6", "G4u6b": "G4u6", "G4u6c": "G4u6",
    "G4u7a": "G4u7", "G4u7b": "G4u7", "G4u7c": "G4u7", "G4u7d": "G4u7",
    "G4u8a": "G4u8", "G4u8b": "G4u8", "G4u8c": "G4u8", "G4u8d": "G4u8",
    "G4u8e": "G4u8", "G4u8f": "G4u8", "G4u8g": "G4u8",
    "G4u9a": "G4u9", "G4u9b": "G4u9", "G4u9c": "G4u9", "G4u9d": "G4u9", "G4u9e": "G4u9",
    "G4u13a": "G4u13", "G4u13b": "G4u13", "G4u13c": "G4u13",
    "G4u14a": "G4u14", "G4u14b": "G4u14",
    "K1a": "K1", "K1b": "K1",
    "K2a": "K2", "K2b": "K2", "K2c": "K2", "K2d": "K2", "K2e": "K2",
    "K3a": "K3", "K3b": "K3", "K3c": "K3",
    "K4a": "K4", "K4b": "K4",
}


def unit_of(row: str) -> str:
    return _UNIT_OF_LETTERED.get(row, row)


ROW_UNITS: dict[str, int] = {"G4": 14, "R12": 2, "L7": 3}
LABELED_UNITS: tuple[str, ...] = tuple(f"K{number}" for number in range(1, 6))

#: Cut-3 checks a cut-12 arm cites beside its own durable check — the one
#: permitted overlap with a prior cut's declared checks, and exactly which.
CO_CITED: dict[str, tuple[str, ...]] = {
    "G4u12": ("test_spec.py::test_g4_a_discarded_failed_attempt_is_undetectable",),
}
