"""The world layer: closed manifests, the rules store, and pure derivation.

Slice 1's registry lives in `beliefs.world.registry`, slice 2's rules store in
`beliefs.world.rules`, its epoch carrier and publication in
`beliefs.world.epoch`, its pure derivations in `beliefs.world.derive` and its
read surface in `beliefs.world.read`; slice 3's log-anchoring codecs and the two acts over
them — the anchor act and the head export — in
`beliefs.world.anchors`, its Science-typed chain views in
`beliefs.world.logmodel` and the engine seam every verification act is handed
in `beliefs.world.verify`; this module is the package's import
surface and re-exports them unchanged. The private names below are the seams
`beliefs.root`, `beliefs.corpus`, and the suite already reach for through
`beliefs.world`, kept importable so the promotion moves no caller. Anything
that *replaces* one of them — a monkeypatched global — must patch the module
where the binding the implementation reads lives.
"""

from __future__ import annotations

from beliefs.world.anchors import (
    HEAD_ARTIFACT_DOMAIN,
    LOG_HEAD_DOMAIN,
    WORLD_GENESIS_DOMAIN,
    AnchorActOrigin,
    BuildOrigin,
    CorpusSubject,
    HeadArtifact,
    LogHeadOrigin,
    LogHeadRecord,
    StoreSubject,
    Subject,
    WorldSubject,
    decode_head_artifact,
    head_artifact_bytes,
    log_head_digest,
    log_head_projection,
    log_head_record_bytes,
    parse_log_head_record,
)
from beliefs.world.derive import (
    BELIEF_INPUT_KIND,
    CERTIFICATION_INVENTORY_DOMAIN,
    COREFERENCE_MAP_DOMAIN,
    PRODUCER_SNAPSHOT_DOMAIN,
    RECEIPT_OUTCOMES,
    RETRACTION_ENUMERATION_DOMAIN,
    SUBJECT_DOMAINS,
    Capture,
    CapturedCertification,
    CapturedCoreference,
    CapturedCorpus,
    CapturedRecord,
    CapturedRetraction,
    CertificationInventory,
    CoreferenceMap,
    DerivationReceipt,
    ProducerSnapshot,
    ReceiptKind,
    ReceiptOutcome,
    address_map,
    address_map_projection,
    belief_input_identity,
    certification_inventory,
    coreference_map,
    derivation_receipts,
    producer_snapshot,
    producers_map_projection,
    retraction_discovery_map,
    retraction_discovery_map_projection,
    retraction_enumeration,
    retraction_enumeration_identity,
    retraction_enumeration_projection,
    subject_identity,
    subject_projection,
)
from beliefs.world.epoch import (
    CURRENT_POINTER,
    DERIVATION_KINDS,
    ENUMERATED_SOURCE_KINDS,
    EPOCH_DOMAIN,
    EPOCH_MEMBERS,
    MEMBER_KEYS,
    RECEIPT_DOMAIN,
    RECEIPT_IDENTITY_KEYS,
    RECEIPT_KEYS,
    RECEIPT_KINDS,
    RETRACTION_RESOLUTIONS,
    SNAPSHOT_SUBJECT,
    DerivationBindings,
    Epoch,
    EpochDeletionReport,
    SeveredIdentity,
    build_epoch,
    delete_epoch,
    packaging_identity_of,
    receipt_identity,
)
from beliefs.world.logmodel import (
    DEFECT_KINDS,
    AbsentView,
    ChainHead,
    ChainView,
    DefectKind,
    DefectView,
    EntryView,
    GenesisEntryView,
    IntentEntryView,
    MalformedView,
    RegisteredEntryView,
    SettledEntryView,
    WellFormedView,
)
from beliefs.world.read import (
    EDGE_STATES,
    BoundStamp,
    EdgeAnswer,
    Location,
    NotPresent,
    Resolved,
    Unknown,
    coreference_edge,
    current_epoch,
    expand_coreference,
    open_epoch,
    resolve_address,
    validate_receipt,
)
from beliefs.world.registry import (
    AdmissionProvenance,
    AdmissionRecord,
    CorpusManifest,
    CorpusStatus,
    ForkedFrom,
    ForkOf,
    Fresh,
    RegistryView,
    ReplicaOf,
    StatusRecord,
    World,
    WorldConfig,
    admission_digest,
    admission_projection,
    corpus_state_identity,
    load_manifest,
    manifest_bytes,
    manifest_projection,
    provenance_projection,
    status_digest,
    status_projection,
)
from beliefs.world.registry import _lift_json as _lift_json
from beliefs.world.registry import _load_world_mirror as _load_world_mirror
from beliefs.world.registry import _parse_manifest as _parse_manifest
from beliefs.world.registry import _world_lock_for as _world_lock_for
from beliefs.world.registry import _world_mirror_bytes as _world_mirror_bytes
from beliefs.world.rules import (
    FIXTURE_SET_DOMAIN,
    RULE_DOMAIN,
    RuleBinding,
    RuleBundle,
    RuleRemovalReport,
    binding_for,
    fixture_set_identity,
    implementation_identity,
    install_rule_binding,
    member_content_digest,
    parse_rule_document,
    remove_rule_binding,
    rule_document_bytes,
    rule_identity,
    shipped_rule_bundles,
)
from beliefs.world.rules import _HeldRule as _HeldRule
from beliefs.world.rules import _resolve_rule_binding as _resolve_rule_binding
from beliefs.world.verify import (
    LogSeam,
    PresentedIdentity,
    PresentedManifest,
    PresentedWorldIds,
)

__all__ = [
    "BELIEF_INPUT_KIND",
    "CERTIFICATION_INVENTORY_DOMAIN",
    "COREFERENCE_MAP_DOMAIN",
    "CURRENT_POINTER",
    "DEFECT_KINDS",
    "DERIVATION_KINDS",
    "EDGE_STATES",
    "ENUMERATED_SOURCE_KINDS",
    "EPOCH_DOMAIN",
    "EPOCH_MEMBERS",
    "FIXTURE_SET_DOMAIN",
    "HEAD_ARTIFACT_DOMAIN",
    "LOG_HEAD_DOMAIN",
    "MEMBER_KEYS",
    "PRODUCER_SNAPSHOT_DOMAIN",
    "RECEIPT_DOMAIN",
    "RECEIPT_IDENTITY_KEYS",
    "RECEIPT_KEYS",
    "RECEIPT_KINDS",
    "RECEIPT_OUTCOMES",
    "RETRACTION_ENUMERATION_DOMAIN",
    "RETRACTION_RESOLUTIONS",
    "RULE_DOMAIN",
    "SNAPSHOT_SUBJECT",
    "SUBJECT_DOMAINS",
    "WORLD_GENESIS_DOMAIN",
    "AbsentView",
    "AdmissionProvenance",
    "AdmissionRecord",
    "AnchorActOrigin",
    "BoundStamp",
    "BuildOrigin",
    "Capture",
    "CapturedCertification",
    "CapturedCoreference",
    "CapturedCorpus",
    "CapturedRecord",
    "CapturedRetraction",
    "CertificationInventory",
    "ChainHead",
    "ChainView",
    "CoreferenceMap",
    "CorpusManifest",
    "CorpusStatus",
    "CorpusSubject",
    "DefectKind",
    "DefectView",
    "DerivationBindings",
    "DerivationReceipt",
    "EdgeAnswer",
    "EntryView",
    "Epoch",
    "EpochDeletionReport",
    "ForkOf",
    "ForkedFrom",
    "Fresh",
    "GenesisEntryView",
    "HeadArtifact",
    "IntentEntryView",
    "Location",
    "LogHeadOrigin",
    "LogHeadRecord",
    "LogSeam",
    "MalformedView",
    "NotPresent",
    "PresentedIdentity",
    "PresentedManifest",
    "PresentedWorldIds",
    "ProducerSnapshot",
    "ReceiptKind",
    "ReceiptOutcome",
    "RegisteredEntryView",
    "RegistryView",
    "ReplicaOf",
    "Resolved",
    "RuleBinding",
    "RuleBundle",
    "RuleRemovalReport",
    "SettledEntryView",
    "SeveredIdentity",
    "StatusRecord",
    "StoreSubject",
    "Subject",
    "Unknown",
    "WellFormedView",
    "World",
    "WorldConfig",
    "WorldSubject",
    "address_map",
    "address_map_projection",
    "admission_digest",
    "admission_projection",
    "belief_input_identity",
    "binding_for",
    "build_epoch",
    "certification_inventory",
    "coreference_edge",
    "coreference_map",
    "corpus_state_identity",
    "current_epoch",
    "decode_head_artifact",
    "delete_epoch",
    "derivation_receipts",
    "expand_coreference",
    "fixture_set_identity",
    "head_artifact_bytes",
    "implementation_identity",
    "install_rule_binding",
    "load_manifest",
    "log_head_digest",
    "log_head_projection",
    "log_head_record_bytes",
    "manifest_bytes",
    "manifest_projection",
    "member_content_digest",
    "open_epoch",
    "packaging_identity_of",
    "parse_log_head_record",
    "parse_rule_document",
    "producer_snapshot",
    "producers_map_projection",
    "provenance_projection",
    "receipt_identity",
    "remove_rule_binding",
    "resolve_address",
    "retraction_discovery_map",
    "retraction_discovery_map_projection",
    "retraction_enumeration",
    "retraction_enumeration_identity",
    "retraction_enumeration_projection",
    "rule_document_bytes",
    "rule_identity",
    "shipped_rule_bundles",
    "status_digest",
    "status_projection",
    "subject_identity",
    "subject_projection",
    "validate_receipt",
]
