"""Frozen cut-45 declaration: 34 units and 34 independent mutation arms."""

from n2_arms import Arm, Sabotage

DECLARATION_UNITS = (
    'G10-a',
    'G10-b',
    'G10-c',
    'G10-d',
    'G10-e',
    'G10-f',
    'G11-a',
    'G11-b',
    'G11-c',
    'G11-d',
    'G11-e',
    'G11-f',
    'G12-a',
    'G12-b',
    'G12-c',
    'G12-d',
    'G12-e',
    'G12-f',
    'G12-g',
    'G12-h',
    'G12-i',
    'G12-j',
    'G12-k',
    'G12-l',
    'G13-a',
    'G13-b',
    'G13-c',
    'G13-d',
    'G13-e',
    'G13-f',
    'G13-g',
    'G13-h',
    'G13-i',
    'G13-j',
)
UNIT_CHECKS = {
    'G10-a': 'test_acceptance.py::test_g10_a_all_assessments_rejected',
    'G10-b': 'test_acceptance.py::test_g10_b_contradictory_twin',
    'G10-c': 'test_acceptance.py::test_g10_c_malformed_assessment',
    'G10-d': 'test_acceptance.py::test_g10_d_canonical_holder',
    'G10-e': 'test_acceptance.py::test_g10_e_manifest_preflight',
    'G10-f': 'test_acceptance.py::test_g10_f_accepted_attribution',
    'G11-a': 'test_acceptance.py::test_g11_a_rejected_failure',
    'G11-b': 'test_acceptance.py::test_g11_b_rejected_pass',
    'G11-c': 'test_acceptance.py::test_g11_c_rejected_superseder',
    'G11-d': 'test_acceptance.py::test_g11_d_failure_names_rejected_twin',
    'G11-e': 'test_acceptance.py::test_g11_e_pass_names_rejected_twin',
    'G11-f': 'test_acceptance.py::test_g11_f_edge_scope',
    'G12-a': 'test_acceptance.py::test_g12_a_node_retraction',
    'G12-b': 'test_acceptance.py::test_g12_b_route_retraction',
    'G12-c': 'test_acceptance.py::test_g12_c_counter_retraction',
    'G12-d': 'test_acceptance.py::test_g12_d_changed_chain_receipt',
    'G12-e': 'test_acceptance.py::test_g12_e_malformed_snapshot_candidate',
    'G12-f': 'test_acceptance.py::test_g12_f_accepted_snapshot_chain',
    'G12-g': 'test_acceptance.py::test_g12_g_mapped_oracle',
    'G12-h': 'test_acceptance.py::test_g12_h_split_with_exclusion',
    'G12-i': 'test_acceptance.py::test_g12_i_unchanged_receipt',
    'G12-j': 'test_acceptance.py::test_g12_j_snapshot_root',
    'G12-k': 'test_acceptance.py::test_g12_k_snapshot_history',
    'G12-l': 'test_acceptance.py::test_g12_l_accept_all_refusal_parity',
    'G13-a': 'test_acceptance.py::test_g13_a_policy_validation',
    'G13-b': 'test_acceptance.py::test_g13_b_complete_report',
    'G13-c': 'test_acceptance.py::test_g13_c_early_error',
    'G13-d': 'test_acceptance.py::test_g13_d_late_error',
    'G13-e': 'test_acceptance.py::test_g13_e_late_absence',
    'G13-f': 'test_acceptance.py::test_g13_f_supplied_context',
    'G13-g': 'test_acceptance.py::test_g13_g_pure_incomplete',
    'G13-h': 'test_acceptance.py::test_g13_h_closure_statement',
    'G13-i': 'test_acceptance.py::test_g13_i_two_policies',
    'G13-j': 'test_acceptance.py::test_g13_j_capture_integrity',
}
CO_CITED = ()

def unit_of(row: str) -> str:
    if row not in DECLARATION_UNITS:
        raise ValueError(f"{row!r} is not a cut-45 row")
    return row


def _arm(row, module, assertion, before, after):
    return Arm(row=row, asserts=assertion, sabotage=Sabotage(module=module, before=before, after=after), checks=(UNIT_CHECKS[unit_of(row)],))


CUT45_ARMS = (
    _arm('G10-a', 'evaluation.py', 'Bypass assessment selection',
         '        if not accepted:\n            continue\n',
         '        if False:\n            continue\n'),
    _arm('G10-b', 'evaluation.py', 'Bypass assessment selection before collapse',
         '        verification_targets.add(node.id)\n        if not accepted:\n            continue\n',
         '        verification_targets.add(node.id)\n        if False:\n            continue\n'),
    _arm('G10-c', 'evaluation.py', 'Move assessment decode ahead of selection',
         '        accepted = counts is None or counts(cast(str, corpus_id), node.id)\n        # beliefs-010c6e:',
         '        accepted = True\n        # beliefs-010c6e:'),
    _arm('G10-d', 'evaluation.py', 'Pass a deprecated assessment address',
         '        accepted = counts is None or counts(cast(str, corpus_id), node.id)\n',
         '        accepted = counts is None or counts(cast(str, corpus_id), (node.deprecated_ids[0] if node.deprecated_ids else node.id))\n'),
    _arm('G10-e', 'evaluation.py', 'Skip filtered local manifest preflight',
         '    counts = None if selection.policy is None else selection.counts\n    local_corpus = view.corpus_id if counts is not None and not world else None\n',
         '    counts = None\n    local_corpus = view.corpus_id if counts is not None and not world else None\n'),
    _arm('G10-f', 'evaluation.py', 'Attribute a rejected twin',
         '        if not accepted:\n            continue\n        visited.add(node.id)\n',
         '        if not accepted:\n            if world:\n                identity = stored.assessment_value(node, profile=profile).identity()\n                attribution.setdefault(identity, set()).add(cast(str, corpus_id))\n            continue\n        visited.add(node.id)\n'),
    _arm('G11-a', 'evaluation.py', 'Bypass verification selection for a failure',
         '        if counts is not None and not counts(cast(str, corpus_id), node.id):\n            continue\n',
         '        if False:\n            continue\n'),
    _arm('G11-b', 'evaluation.py', 'Bypass verification selection for a pass',
         '        if node.kind != "verification":\n            continue\n        if counts is not None and not counts(cast(str, corpus_id), node.id):\n            continue\n',
         '        if node.kind != "verification":\n            continue\n        if False:\n            continue\n'),
    _arm('G11-c', 'evaluation.py', 'Include rejected superseding verification',
         '        if counts is not None and not counts(cast(str, corpus_id), node.id):\n            continue\n        names = {r.target for r in node.relations if r.predicate == stored.VERIFIES}\n',
         '        if False:\n            continue\n        names = {r.target for r in node.relations if r.predicate == stored.VERIFIES}\n'),
    _arm('G11-d', 'evaluation.py', 'Populate verification targets from accepted assessments only',
         '        verification_targets.add(node.id)\n',
         '        if accepted:\n            verification_targets.add(node.id)\n'),
    _arm('G11-e', 'evaluation.py', 'Test verifies membership against visited',
         '        if not any(view.resolve(name) in verification_targets for name in names if view.resolve(name) is not None):\n',
         '        if not any(view.resolve(name) in visited for name in names if view.resolve(name) is not None):\n'),
    _arm('G11-f', 'evaluation.py', 'Union verification targets into correction scope',
         '    scope = visited | verification_ids | set(snapshot.bases)\n',
         '    scope = visited | verification_targets | verification_ids | set(snapshot.bases)\n'),
    _arm('G12-a', 'evaluation.py', 'Bypass ordinary retraction selection',
         '            if not counts(holder, canonical):\n                continue\n',
         '            if False:\n                continue\n'),
    _arm('G12-b', 'evaluation.py', 'Retire a rejected route target',
         '            if not counts(holder, canonical):\n                continue\n        else:\n            canonical = ref\n',
         '            if False:\n                continue\n        else:\n            canonical = ref\n'),
    _arm('G12-c', 'evaluation.py', 'Include rejected counters in facets',
         '            assert holder is not None\n            if not counts(holder, canonical):\n                continue\n',
         '            assert holder is not None\n            if False:\n                continue\n'),
    _arm('G12-d', 'evaluation.py', 'Require receipt comparison despite excluded transitive counter',
         '            if ref not in affected and computed != receipt[ref]:\n',
         '            if computed != receipt[ref]:\n'),
    _arm('G12-e', 'corpus.py', 'Validate snapshot facet before selection',
         '            if counts is not None and not counts(corpus_id, node.id):\n                continue\n',
         '            _validated_retraction_facet(node)\n            if counts is not None and not counts(corpus_id, node.id):\n                continue\n'),
    _arm('G12-f', 'corpus.py', 'Omit accepted chain-member validation',
         '        for ref in sorted(members):\n',
         '        for ref in ():\n'),
    _arm('G12-g', 'evaluation.py', 'Use full captured resolver for L_c',
         '        local = view._mapped_view(corpus_id)\n',
         '        local = view._captured_views[corpus_id]\n'),
    _arm('G12-h', 'evaluation.py', 'Skip L_c-vs-W comparison',
         '            if world_computed != computed:\n',
         '            if False:\n'),
    _arm('G12-i', 'evaluation.py', 'Disable all receipt checks on any exclusion',
         '            if ref not in affected and computed != receipt[ref]:\n                raise RetractionResolutionDisagreement(ref, receipt[ref], computed)\n',
         '            if not selection._decisions and computed != receipt[ref]:\n                raise RetractionResolutionDisagreement(ref, receipt[ref], computed)\n'),
    _arm('G12-j', 'evaluation.py', 'Use unrestricted snapshot fold',
         '        snapshot_standing = view.snapshot_standing(counts=counts)\n',
         '        snapshot_standing = view.snapshot_standing()\n'),
    _arm('G12-k', 'evaluation.py', 'Reuse unfiltered cached history',
         '        history = snapshot_standing.history.get(bound, ())\n',
         '        history = view.snapshot_standing().history.get(bound, ())\n'),
    _arm('G12-l', 'evaluation.py', 'Omit filtered receipt-fidelity check',
         '        for ref in surviving:\n            computed = RETRACTION_UPHELD if local_standing[ref] else RETRACTION_OVERTURNED\n            if ref not in affected and computed != receipt[ref]:\n',
         '        for ref in surviving:\n            computed = RETRACTION_UPHELD if local_standing[ref] else RETRACTION_OVERTURNED\n            if False:\n'),
    _arm('G13-a', 'evaluation.py', 'Coerce result with bool instead of rejecting',
         '            if type(result) is not bool:\n                raise MalformedRecord("acceptance-result-not-bool")\n',
         '            result = bool(result)\n'),
    _arm('G13-b', 'evaluation.py', 'Apply relation matching before predicate',
         '        accepted = counts is None or counts(cast(str, corpus_id), node.id)\n        # beliefs-010c6e: membership by the `assesses` edge, before any decode.\n        targets = [r.target for r in node.relations if r.predicate == stored.ASSESSES]\n        wanted = view.resolve(proposition) or proposition\n        if not any((view.resolve(target) or target) == wanted for target in targets):\n            continue  # a lookup, not a value handed out — membership by the edge, never by decoding\n',
         '        # beliefs-010c6e: membership by the `assesses` edge, before any decode.\n        targets = [r.target for r in node.relations if r.predicate == stored.ASSESSES]\n        wanted = view.resolve(proposition) or proposition\n        if not any((view.resolve(target) or target) == wanted for target in targets):\n            continue  # a lookup, not a value handed out — membership by the edge, never by decoding\n        accepted = counts is None or counts(cast(str, corpus_id), node.id)\n'),
    _arm('G13-c', 'evaluation.py', 'Expose decisions while incomplete',
         '        return self._decisions[key]\n',
         '        self.finish()\n        return self._decisions[key]\n'),
    _arm('G13-d', 'evaluation.py', 'Reset report in exception handler',
         '        return Refused(f"consulted-contracts-disagree: {exc}", acceptance=selection.report), NotReached(), None\n',
         '        return Refused(f"consulted-contracts-disagree: {exc}", acceptance=None if acceptance is None else AcceptanceContext(acceptance.statement, (), False)), NotReached(), None\n'),
    _arm('G13-e', 'evaluation.py', 'Mark every absence incomplete',
         '        return NoBelief("unavailable-corpus-absent", detail=f"inputs recorded in absent corpora: {corpora}", acceptance=selection.report), NotReached(), None\n',
         '        return NoBelief("unavailable-corpus-absent", detail=f"inputs recorded in absent corpora: {corpora}", acceptance=None if acceptance is None else AcceptanceContext(acceptance.statement, (), False)), NotReached(), None\n'),
    _arm('G13-f', 'evaluation.py', 'Remove supplied-acceptance guard',
         '    if context.acceptance is not None:\n        raise MalformedRecord("supplied-acceptance-context")\n',
         '    if False:\n        raise MalformedRecord("supplied-acceptance-context")\n'),
    _arm('G13-g', 'belief.py', 'Remove pure incomplete guard',
         '    if context.acceptance is not None and not context.acceptance.complete:\n',
         '    if False:\n'),
    _arm('G13-h', 'closure.py', 'Omit acceptance_policy from projection',
         '    if acceptance_statement is not None:\n        projection["acceptance_policy"] = acceptance_statement\n',
         '    if False:\n        projection["acceptance_policy"] = acceptance_statement\n'),
    _arm('G13-i', 'world/view.py', 'Return unrestricted snapshot cache on filtered call',
         '        if counts is not None:\n            return snapshot_standing(self._captured_views, counts=counts)\n',
         '        if counts is not None:\n            return self.snapshot_standing()\n'),
    _arm('G13-j', 'evaluation.py', 'Return rejected-pool answer before coverage checks',
         '        for report in view.damaged():  # the first damaged corpus refuses; the rest are not reported\n            raise CorpusDamaged(f"producer-snapshot:{bound}", report.corpus_id, view.stamp)\n        for corpus_id in view.absent():\n            absent.append((f"producer-snapshot:{bound}", corpus_id))\n',
         '        for report in ():  # the first damaged corpus refuses; the rest are not reported\n            raise CorpusDamaged(f"producer-snapshot:{bound}", report.corpus_id, view.stamp)\n        for corpus_id in ():\n            absent.append((f"producer-snapshot:{bound}", corpus_id))\n'),
)
