"""Frozen cut-46 declaration: 36 units and 36 independent mutation arms."""

from n2_arms import Arm, Sabotage

DECLARATION_UNITS = ('Y5-c', 'Y5-d', 'Y5-e', 'Y17-a', 'Y17-b', 'Y17-c', 'Y17-d', 'Y17-e', 'Y17-f', 'Y17-g', 'Y17-h', 'Y17-i', 'Y17-j', 'Y17-k', 'Y17-l', 'Y17-m', 'Y17-n', 'Y17-o', 'Y17-p', 'Y18-a', 'Y18-b', 'Y18-c', 'Y18-d', 'Y18-e', 'Y18-f', 'Y18-g', 'Y18-h', 'Y18-i', 'Y18-j', 'Y18-k', 'Y18-l', 'Y18-m', 'Y18-n', 'Y18-o', 'Y18-p', 'Y18-q')
UNIT_CHECKS = {'Y5-c': 'test_publication_attribution.py::test_y5_c_v3_destination_pins', 'Y5-d': 'test_publication_attribution.py::test_y5_d_v3_disagreement', 'Y5-e': 'test_publication_attribution.py::test_y5_e_v2_pin_precedence', 'Y17-a': 'test_publication_attribution.py::test_y17_a_local_holdings', 'Y17-b': 'test_publication_attribution.py::test_y17_b_first_carry', 'Y17-c': 'test_publication_attribution.py::test_y17_c_forwarded_origin', 'Y17-d': 'test_publication_attribution.py::test_y17_d_selection_scope', 'Y17-e': 'test_publication_attribution.py::test_y17_e_distinct_holders', 'Y17-f': 'test_publication_attribution.py::test_y17_f_v2_refusal', 'Y17-g': 'test_publication_attribution.py::test_y17_g_before_intent', 'Y17-h': 'test_publication_attribution.py::test_y17_h_markerless_replica', 'Y17-i': 'test_publication_attribution.py::test_y17_i_missing_holder', 'Y17-j': 'test_publication_attribution.py::test_y17_j_invalid_source_order', 'Y17-k': 'test_publication_attribution.py::test_y17_k_admission_before_layout', 'Y17-l': 'test_publication_attribution.py::test_y17_l_held_capture', 'Y17-m': 'test_publication_attribution.py::test_y17_m_local_frozen_marker', 'Y17-n': 'test_publication_attribution.py::test_y17_n_remote_frozen_marker', 'Y17-o': 'test_publication_attribution.py::test_y17_o_registry_boundary', 'Y17-p': 'test_publication_attribution.py::test_y17_p_legacy_source', 'Y18-a': 'test_publication_attribution.py::test_y18_a_closed_shapes', 'Y18-b': 'test_publication_attribution.py::test_y18_b_member_types', 'Y18-c': 'test_publication_attribution.py::test_y18_c_strict_order', 'Y18-d': 'test_publication_attribution.py::test_y18_d_selected_addresses', 'Y18-e': 'test_publication_attribution.py::test_y18_e_identity_split', 'Y18-f': 'test_publication_attribution.py::test_y18_f_snapshot_formats', 'Y18-g': 'test_publication_attribution.py::test_y18_g_snapshot_commitment', 'Y18-h': 'test_publication_attribution.py::test_y18_h_snapshot_tamper', 'Y18-i': 'test_publication_attribution.py::test_y18_i_snapshot_pin', 'Y18-j': 'test_publication_attribution.py::test_y18_j_staged_release', 'Y18-k': 'test_publication_attribution.py::test_y18_k_audit_release', 'Y18-l': 'test_publication_attribution.py::test_y18_l_arrival_release', 'Y18-m': 'test_publication_attribution.py::test_y18_m_tip_release', 'Y18-n': 'test_publication_attribution.py::test_y18_n_source_release', 'Y18-o': 'test_publication_attribution.py::test_y18_o_remote_release', 'Y18-p': 'test_publication_attribution.py::test_y18_p_v3_succession', 'Y18-q': 'test_publication_attribution.py::test_y18_q_explicit_activation'}
CO_CITED = ()

def unit_of(row: str) -> str:
    if row not in DECLARATION_UNITS:
        raise ValueError(f"{row!r} is not a cut-46 row")
    return row


def _arm(row, module, assertion, before, after):
    return Arm(row=row, asserts=assertion, sabotage=Sabotage(module=module, before=before, after=after), checks=(UNIT_CHECKS[unit_of(row)],))


CUT46_ARMS = (
    _arm('Y5-c', 'publish_request.py', '`v3_destination_pins`: v2/v3 source coordination pins are replaced by writer v3; other domains are unioned',
         '            if coordination == V3_PIN and namespace == "coordination":\n',
         '            if False:\n'),
    _arm('Y5-d', 'publish_request.py', '`v3_disagreement`: base and non-coordination mismatch refuse with exact field/corpus ids',
         '            if domains.setdefault(namespace, pin) != pin:\n',
         '            if domains.setdefault(namespace, pin) != pin and coordination != V3_PIN:\n'),
    _arm('Y5-e', 'publish_request.py', '`v2_pin_precedence`: source v3 plus writer v2 refuses coordination disagreement before preparation scan/intent',
         '            if coordination == V3_PIN and namespace == "coordination":\n                continue\n',
         '            if coordination in PUBLISHING_COORDINATION and namespace == "coordination":\n                continue\n'),
    _arm('Y17-a', 'publish.py', '`local_holdings`: Fresh/ForkOf yield None under v2 and empty tuple under v3',
         '    replicas = tuple(holder for holder in sorted(grouped) if type(admissions[holder].provenance) is ReplicaOf)\n',
         '    replicas = tuple(holder for holder in sorted(grouped) if type(admissions[holder].provenance) is not ReplicaOf)\n'),
    _arm('Y17-b', 'publish.py', '`first_carry`: each selected world kind gets holder and own marker uid',
         '            result.append(earlier.get(ref, (ref, holder, uid)))\n',
         '            if ref in earlier:\n                result.append(earlier[ref])\n'),
    _arm('Y17-c', 'publish.py', '`forwarded_origin`: earlier tuple is copied exactly',
         '            uid, earlier = sources[holder]\n            result.append(earlier.get(ref, (ref, holder, uid)))\n',
         '            uid, earlier = sources[holder]\n            result.append((ref, holder, uid))\n'),
    _arm('Y17-d', 'publish.py', '`selection_scope`: no unselected source attribution escapes',
         '            result.append(earlier.get(ref, (ref, holder, uid)))\n    return tuple(result)\n',
         '            result.append(earlier.get(ref, (ref, holder, uid)))\n    leaked = {row[0]: row for _, earlier in sources.values() for row in earlier.values()} | {row[0]: row for row in result}\n    return tuple(leaked[ref] for ref in sorted(leaked))\n'),
    _arm('Y17-e', 'publish.py', '`distinct_holders`: canonical selected keys and per-holder origins, ascending',
         '            uid, earlier = sources[holder]\n',
         '            uid, earlier = next(iter(sources.values()))\n'),
    _arm('Y17-f', 'publish.py', '`v2_refusal`: exact unpinned reason and all selected replica ids ascending',
         '        if replicas:\n            raise PublicationRefused("attribution-contract-unpinned", corpus_ids=replicas)\n',
         '        if False:\n            raise PublicationRefused("attribution-contract-unpinned", corpus_ids=replicas)\n'),
    _arm('Y17-g', 'publish.py', '`before_intent`: v2 refusal runs before `_open_publication` and leaves ops/written state unchanged',
         '    attributions = _selected_attributions(read, world.registry(), selection.selected, pins.domains["coordination"])\n',
         '    attributions = _selected_attributions(read, world.registry(), selection.selected, pins.domains["coordination"]) if pins.domains["coordination"] == V3_PIN else None\n'),
    _arm('Y17-h', 'publish.py', '`markerless_replica`: marker-absent refuses, not an own-only classification',
         '        manifest = read.captured_manifest(holder)\n        try:\n            require_publication_layout(records)\n',
         '        manifest = read.captured_manifest(holder)\n        if not any(node.kind == MARKER_KIND for node in records):\n            continue\n        try:\n            require_publication_layout(records)\n'),
    _arm('Y17-i', 'publish.py', '`missing_holder`: v2/v3 missing admission reports first holder and ascending refs',
         '    for holder in sorted(grouped):\n        if holder not in admissions:\n            raise PublicationRefused(\n                "attribution-holder-unregistered", corpus_ids=(holder,), refs=tuple(sorted(grouped[holder])),\n            )\n    replicas = tuple(holder for holder in sorted(grouped) if type(admissions[holder].provenance) is ReplicaOf)\n',
         '    replicas = tuple(holder for holder in sorted(grouped) if holder in admissions and type(admissions[holder].provenance) is ReplicaOf)\n'),
    _arm('Y17-j', 'publish.py', '`invalid_source_order`: reverse input order still reports ascending first invalid holder',
         '    for holder in replicas:\n        records = read.captured_records(holder)\n',
         '    for holder in (record.corpus_id for record in registry.admissions if record.corpus_id in replicas):\n        records = read.captured_records(holder)\n'),
    _arm('Y17-k', 'publish.py', "`admission_before_layout`: missing admission wins before an earlier holder's invalid marker is inspected",
         '    for holder in sorted(grouped):\n        if holder not in admissions:\n',
         '    for holder in sorted(grouped):\n        if holder in admissions and type(admissions[holder].provenance) is ReplicaOf:\n            try:\n                require_publication_layout(read.captured_records(holder))\n            except PublicationArrivalRefused as refused:\n                raise PublicationRefused("attribution-source-invalid", corpus_ids=(holder,), refs=tuple(sorted(grouped[holder])), field=refused.reason) from refused\n        if holder not in admissions:\n'),
    _arm('Y17-l', 'publish.py', '`held_capture`: preparation uses held records/manifests once per replica, never reopens a root',
         '        records = read.captured_records(holder)\n',
         '        records = tuple(ReadView.opened_at(Path(holder)).iter_stored())\n'),
    _arm('Y17-m', 'publish.py', '`local_frozen_marker`: reconstruction forwards frozen local origins, with source access trapped',
         '        attributions=a.snapshot.attributions,\n',
         '        attributions=None if a.opened.intent.destination.type == "local" else a.snapshot.attributions,\n'),
    _arm('Y17-n', 'publish.py', '`remote_frozen_marker`: reconstruction forwards frozen remote origins; mark-only recovery uses export',
         '        a.opened.intent, world_id=a.request.world_id, epoch=a.request.epoch, selection=tuple(i for i, _ in a.snapshot.records),\n        attributions=a.snapshot.attributions,\n',
         '        a.opened.intent, world_id=a.request.world_id, epoch=a.request.epoch, selection=tuple(i for i, _ in a.snapshot.records),\n        attributions=None if a.opened.intent.destination.type == "remote" else a.snapshot.attributions,\n'),
    _arm('Y17-o', 'publish.py', '`registry_boundary`: once-per-new-publish scan, retained retired admission, scan error before intent',
         '    admissions = {record.corpus_id: record for record in registry.admissions}\n',
         '    admissions = {record.corpus_id: record for record in registry.admissions if not any(status.corpus_id == record.corpus_id for status in registry.statuses)}\n'),
    _arm('Y17-p', 'publish.py', '`legacy_source`: unattributed v2 B falls back to B; explicit v3 B forwards A',
         '        if holder in sources:\n            uid, earlier = sources[holder]\n            result.append(earlier.get(ref, (ref, holder, uid)))\n',
         '        if holder in sources:\n            uid, earlier = sources[holder]\n            source_marker = next(node for node in read.captured_records(holder) if node.kind == MARKER_KIND)\n            result.append(earlier.get(ref, (ref, source_marker.facets[stored.COORDINATION_FACET]["published_from"]["world_id"], uid)))\n'),
    _arm('Y18-a', 'publication.py', '`closed_shapes`: exactly old/new nested maps; old marker bytes remain exact',
         '    if type(source) is not dict or set(source) not in ({"world_id", "epoch", "view"}, {"world_id", "epoch", "view", "attributions"}):\n',
         '    if type(source) is not dict:\n'),
    _arm('Y18-b', 'publication.py', '`member_types`: malformed containers/triples/mixed members return malformed or factory/codec refusal',
         '    if type(value) is not list:\n        return True\n    for row in value:\n',
         '    if type(value) not in (list, tuple):\n        return True\n    for row in value:\n'),
    _arm('Y18-c', 'publication.py', '`strict_order`: duplicate and descending keys refuse, including valid-empty distinction',
         '    return addresses != sorted(set(addresses))\n',
         '    return False\n'),
    _arm('Y18-d', 'publication.py', '`selected_addresses`: invalid world ids and unselected keys refuse',
         '            or not _world_record_id(row[0]) or row[0] not in selection\n',
         '            or not _world_record_id(row[0])\n'),
    _arm('Y18-e', 'publication.py', '`identity_split`: same intent/different origins keep uid/address/id, change content and remain consistent',
         '    node = _node(MARKER_KIND, address, marker_uid(intent.event_token), facet, ())\n',
         '    node = _node(MARKER_KIND, address, v1.digest(_MARKER_UID_DOMAIN, [intent.event_token, attributions])[:32], facet, ())\n'),
    _arm('Y18-f', 'publish_request.py', '`snapshot_formats`: old bytes and new bytes round-trip exactly; missing/empty remain distinct',
         '    attributions = None\n    if "attributions" in value:\n',
         '    attributions = ()\n    if "attributions" in value:\n'),
    _arm('Y18-g', 'publish_request.py', '`snapshot_commitment`: origin-only change moves snapshot identity',
         '        if self.attributions is not None:\n            result["attributions"] = [list(row) for row in self.attributions]\n',
         '        if False:\n            result["attributions"] = [list(row) for row in self.attributions]\n'),
    _arm('Y18-h', 'publish.py', '`snapshot_tamper`: origin edit reports mismatch, malformed entry reports undecodable',
         '    if snapshot.identity() != request.selection or snapshot.event_token != intent.event_token:\n',
         '    if snapshot.event_token != intent.event_token:\n'),
    _arm('Y18-i', 'publish.py', '`snapshot_pin`: coherent request/snapshot with wrong pairing reports snapshot-pin-disagrees before stage',
         '    if coordination not in PUBLISHING_COORDINATION or (coordination == V3_PIN) != (snapshot.attributions is not None):\n',
         '    if False:\n'),
    _arm('Y18-j', 'corpus.py', '`staged_release`: shape-valid but unauthorized marker refuses the staged write',
         '                or _marker_release_malformed(node, ("coordination:" + self._profile.activated_contracts["coordination"]) if "coordination" in self._profile.activated_contracts else None)\n',
         ''),
    _arm('Y18-k', 'corpus.py', '`audit_release`: matching profile/manifest plus wrong marker shape yields coordination-facet-malformed',
         '    return publication_content_malformed(node) or (node.kind == MARKER_KIND and _marker_release_malformed(node, coordination_pin))\n',
         '    return publication_content_malformed(node)\n'),
    _arm('Y18-l', 'publication_arrival.py', '`arrival_release`: unauthorized marker refuses marker-malformed before admission',
         '    (marker,) = (node for node in records if node.kind == MARKER_KIND)\n    if _marker_release_malformed(marker, manifest.profile.domains.get("coordination")):\n',
         '    (marker,) = (node for node in records if node.kind == MARKER_KIND)\n    if False:\n'),
    _arm('Y18-m', 'publication_arrival.py', '`tip_release`: unauthorized held marker refuses with its corpus id',
         '            if _marker_release_malformed(marker, manifest.profile.domains.get("coordination")):\n',
         '            if False:\n'),
    _arm('Y18-n', 'publish.py', '`source_release`: unauthorized captured marker reports attribution-source-invalid/marker-malformed',
         '            (marker,) = (node for node in records if node.kind == MARKER_KIND)\n            if _marker_release_malformed(marker, manifest.profile.domains.get("coordination")):\n',
         '            (marker,) = (node for node in records if node.kind == MARKER_KIND)\n            if False:\n'),
    _arm('Y18-o', 'publish.py', '`remote_release`: validated-export marker must agree with export manifest pin',
         '    return not _marker_release_malformed(node, load_manifest(_remote_export(r.op, mark.corpus_id)).profile.domains.get("coordination"))\n',
         '    return True\n'),
    _arm('Y18-p', 'profile.py', '`v3_succession`: v3 names v2 predecessor and retains every outer kind field',
         '    predecessor = None if version == 1 else _shipped_coordination(version - 1)\n',
         '    predecessor = None if version == 1 else _shipped_coordination(1)\n'),
    _arm('Y18-q', 'profile.py', '`explicit_activation`: shipped default remains v2; fresh v3 root works, existing manifest cannot be re-adopted',
         'def shipped_coordination(version: int = 2) -> CoordinationContract:\n',
         'def shipped_coordination(version: int = 3) -> CoordinationContract:\n'),
)
